name: Run Tests on Feature Branch Push

on:
  push:
    branches:
      - "feature/**" # Matches branches like feature/my-new-feature

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Example: If your services depend on external containers like databases
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub (if needed for private images)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}

      - name: Build and start services with Docker Compose
        run: |
          docker-compose build
          docker-compose up -d

      - name: Run tests
        run: |
          # Example: Run tests for service1
          docker-compose run service1 pytest
          # Example: Run tests for service2
          docker-compose run service2 npm test
          # Add more for other services as needed

      - name: Tear down services
        if: always()
        run: docker-compose down
